runtime:
  cache_dir: ./.cache/antora

site:
  title: FastTrack to RHODS
  url: https://erwangranger.github.io/Fastrack-to-RHODS
  start_page: fasttrack-to-rhods::index.adoc


content:
  sources:
    - url: ./
      branches: main
      start_path: doc

asciidoc:
  attributes:
    release-version: main
    page-pagination: true
  extensions:
    - ./lib/tab-block.js
    - ./lib/remote-include-processor.js

ui:
  bundle:
    url: https://github.com/redhat-developer-demos/rhd-tutorial-ui/releases/download/v0.1.9/ui-bundle.zip
    snapshot: true
  supplemental_files: ./supplemental-ui
  ## none of the syntaxes below worked
    # - path: .nojekyll
    # - path: ui.yml
    #   contents: "static_files: [ .nojekyll ]"

  # supplemental_files:
  #   - dir: ./supplemental-ui
  #   # - path: ui.yml
    #   contents: "static_files: [ .nojekyll ]"
    # - path: .nojekyll
    # - dir: ./supplemental-ui

output:
  dir: ./gh-pages
